### ISSUE TITLE
!shouldjoin command says who's not joined

### ISSUE THREAD

**Issue by contiguity** [caitlin/cinch-onuwwgame#34]
Presenting names to the !shouldjoin command filters out those who are joined and then outputs the remaining players to the channel (This may be convenient to add)

**Comment by Chankster** [comment]
Personally I don't think its good etiquette to ping/notify nonplayers in
the channel.  This is why we originally made the invite/subscribe option.

Travis

**Comment by contiguity** [comment]
That's fair; I was simply suggesting sending it the channel with a simple reject loop.

On a related note, are you getting messages when I create issues? I'm mostly creating these as notes to myself (though I appreciate outside feedback) but I don't want to bother you

**Comment by Chankster** [comment]
I do get email notifications but don't mind them at all.

Travis

**Comment by contiguity** [comment]
I might shelve this for now. It seems like an unnecessary feature at this point
