### ISSUE TITLE
Move random / blindrandom into their own command?

### ISSUE THREAD

**Issue by contiguity** [caitlin/cinch-onuwwgame#35]
I'm thinking about moving random and blindrandom into a separate command to clean up the set roles command, which is currently pretty messy.

I'm not sure how much this would affect those who use it, but players I play with would not notice the switch (because they never use it).

**Comment by caitlin** [comment]
Perhaps in a !variant command?

**Comment by contiguity** [comment]
This is part of what I was thinking. This is also partially motivated by making it easier to use the lone wolf variant and fixing #28

**Comment by contiguity** [comment]
Commit pushed and a message exists for the old method
